import { expect, test } from '@playwright/test';
import { MAX_PROJECT_FILE_BYTES } from '../../src/domain/projectSerialization';
import { admissionFixture, savedAdmissionRecord } from './project-admission-support';
import { addCoordinate, normalizedViewport, openInstrumentedMap } from './map-recovery-support';
import { reviewConflict, storedDraft, trackWrites } from './autosave-conflict-support';
import { assertFreshPortable, assertUnobstructedSearch, downloadPortable, importSingleGeoJson, loseOversizedCameraMove, openPortable, portableBoundarySource, portableCameraSnapshot, portableDownload, portableFixture, stageGeoJson, stagePortable } from './portable-budget-support';

test.beforeEach(() => test.setTimeout(180_000));

test('actual 160200-position import autosaves, downloads compact losslessly, and reopens', async ({ page }, testInfo) => {
  await page.goto('./');
  await openPortable(page, await admissionFixture(page));
  const source = await portableBoundarySource(page);
  await importSingleGeoJson(page, source);
  await expect(page.locator('.layer-row')).toHaveCount(201);
  await expect(page.getByRole('status', { name: 'Autosave status' })).toHaveText('All changes saved locally', { timeout: 30_000 });
  const saved = await savedAdmissionRecord(page);
  const downloaded = await downloadPortable(page, testInfo, '160200-boundaries');
  const readableBytes = Buffer.byteLength(JSON.stringify(downloaded.document, null, 2) + '\n');
  expect(readableBytes).toBeGreaterThan(MAX_PROJECT_FILE_BYTES);
  expect(downloaded.bytes).toBeLessThan(MAX_PROJECT_FILE_BYTES);
  expect(downloaded.bytes).toBe(Buffer.byteLength(JSON.stringify(downloaded.document)));
  expect(downloaded.document.layers).toEqual(saved.document.layers);
  expect(await assertFreshPortable(page, downloaded.text)).toMatchObject({ layers: 201 });
  const sourceBytes = Buffer.byteLength(JSON.stringify(source));
  await testInfo.attach('ux-fix-029-original-measurements', { body: JSON.stringify({
    sourceBytes, compactBytes: downloaded.bytes,
    readableBytes, layerCount: 201, positions: 160_200,
  }), contentType: 'application/json' });
  await page.screenshot({ path: testInfo.outputPath('ux-fix-029-boundary-download.png'), animations: 'disabled' });
  await openPortable(page, downloaded.document);
  const reopened = await savedAdmissionRecord(page);
  expect(reopened.document.layers).toEqual(downloaded.document.layers);
  await page.reload();
  await expect(page.locator('.layer-row')).toHaveCount(201);
});

test('true compact overflow is rejected for import, duplicate and scalar edits without losing correctable input or writing autosave', async ({ page }, testInfo) => {
  await page.goto('./');
  const full = await portableFixture(page);
  await openPortable(page, full);
  const original = await savedAdmissionRecord(page);
  await trackWrites(page);
  const dialog = await stageGeoJson(page, { type: 'Feature', properties: { name: 'Extra' }, geometry: { type: 'Point', coordinates: [16.37, 48.21] } });
  await dialog.getByRole('button', { name: 'Import 2 files' }).click();
  await expect(dialog.getByRole('alert')).toContainText('10 MB portable limit');
  await expect(dialog.getByRole('list', { name: 'Selected map data files' })).toContainText('boundaries.geojson');
  await dialog.getByRole('button', { name: 'Cancel', exact: true }).click();
  const width = page.getByRole('spinbutton', { name: 'Page width' });
  await width.fill('298.125'); await width.press('Tab');
  await expect(width).toHaveValue('298.125');
  await expect(width).toHaveAttribute('aria-invalid', 'true');
  await expect(page.locator('.validated-number-field').filter({ has: width }).getByRole('alert')).toContainText('portable limit');
  await page.screenshot({ path: testInfo.outputPath('ux-fix-029-width-retained.png'), animations: 'disabled' });
  await width.fill('297'); await width.press('Tab');
  await expect(width).toHaveAttribute('aria-invalid', 'false');
  await page.getByRole('button', { name: full.title, exact: true }).click();
  const title = page.getByRole('textbox', { name: 'Project title' });
  await title.fill(full.title + ' larger'); await title.press('Enter');
  await expect(title).toHaveAttribute('aria-invalid', 'true');
  await assertUnobstructedSearch(page);
  await title.press('Escape');
  await page.getByRole('button', { name: 'Select Marker 5', exact: true }).click();
  await page.getByRole('button', { name: 'Layer menu', exact: true }).click();
  await page.getByRole('menuitem', { name: 'Duplicate layer', exact: true }).click();
  await expect(page.locator('.properties-panel > [role="alert"]')).toContainText('portable limit');
  for (const [label, value, previous] of [['Layer opacity', '99', '1'], ['Layer name', 'A much longer name', 'Marker 5'], ['POI label', 'A bigger label', 'x']]) {
    const field = page.getByLabel(label, { exact: true });
    await field.fill(value); await field.press('Tab');
    await expect(field).toHaveValue(value);
    await expect(page.locator('.properties-panel [role="alert"]').last()).toContainText('portable limit');
    await field.fill(previous); await field.press('Tab');
  }
  await expect(page.locator('.layer-row')).toHaveCount(207);
  await expect(page.getByRole('button', { name: 'Select Marker 5' })).toHaveAttribute('aria-current', 'true');
  await expect(page.getByRole('button', { name: 'Undo', exact: true })).toBeDisabled();
  expect(await savedAdmissionRecord(page)).toEqual(original);
  expect(await page.evaluate(() => window.conflictInstrumentation.puts)).toBe(0);
  const downloaded = await downloadPortable(page, testInfo, 'exact-cap');
  expect(downloaded.bytes).toBe(MAX_PROJECT_FILE_BYTES);
  expect(downloaded.text.endsWith('\n')).toBe(false);
  expect(await assertFreshPortable(page, downloaded.text)).toMatchObject({ layers: 207 });
  await openPortable(page, downloaded.document);
  await expect(page.locator('.layer-row')).toHaveCount(207);
});

test('native camera rejection restores map, diagnostics and redo; interrupted renderer recovery cannot revive a rejected viewport', async ({ page }, testInfo) => {
  await openInstrumentedMap(page);
  const full = await portableFixture(page);
  await openPortable(page, full);
  await expect(page.getByTestId('map-canvas')).toHaveAttribute('data-map-ready', 'true', { timeout: 30_000 });
  await page.getByLabel('Bearing', { exact: true }).fill('1');
  await page.getByLabel('Bearing', { exact: true }).press('Tab');
  await page.getByRole('button', { name: 'Undo', exact: true }).click();
  await expect(page.getByRole('status', { name: 'Autosave status' })).toHaveText('All changes saved locally');
  await expect(page.getByRole('button', { name: 'Redo', exact: true })).toBeEnabled();
  const saved = await savedAdmissionRecord(page), before = await portableCameraSnapshot(page);
  await trackWrites(page);
  await page.evaluate(() => window.recoveryAudit.map!.jumpTo({ center: [16.123456, 48.123456], zoom: 13.123456, bearing: 30, pitch: 20 }));
  await expect(page.getByRole('alert', { name: 'Camera change not saved' })).toContainText('Previous map view restored');
  expect(normalizedViewport(await portableCameraSnapshot(page))).toEqual(normalizedViewport(saved.document.camera));
  await expect(page.getByTestId('map-canvas')).toHaveAttribute('data-map-center', saved.document.camera.center.join(','));
  await expect(page.getByTestId('map-canvas')).toHaveAttribute('data-map-zoom', String(saved.document.camera.zoom));
  await expect(page.getByRole('button', { name: 'Redo', exact: true })).toBeEnabled();
  const rejected = await portableCameraSnapshot(page);
  expect(rejected.rendererCount).toBe(before.rendererCount);
  await assertUnobstructedSearch(page);
  await page.screenshot({ path: testInfo.outputPath('ux-fix-029-native-camera-rollback.png'), animations: 'disabled' });
  const interrupted = await loseOversizedCameraMove(page);
  const interruptedBytes = Buffer.byteLength(JSON.stringify({ ...saved.document, camera: { ...saved.document.camera, ...normalizedViewport(interrupted) } }));
  expect(interruptedBytes).toBeGreaterThan(MAX_PROJECT_FILE_BYTES);
  await expect(page.getByRole('button', { name: 'Retry map' })).toBeEnabled();
  await page.getByRole('button', { name: 'Retry map' }).click();
  await expect(page.getByTestId('map-canvas')).toHaveAttribute('data-map-ready', 'true', { timeout: 30_000 });
  const recovered = await portableCameraSnapshot(page);
  expect(normalizedViewport(recovered)).toEqual(normalizedViewport(saved.document.camera));
  expect(recovered.rendererCount).toBe(before.rendererCount + 1);
  await expect(page.getByRole('button', { name: 'Redo', exact: true })).toBeEnabled();
  expect(await savedAdmissionRecord(page)).toEqual(saved);
  expect(await page.evaluate(() => window.conflictInstrumentation.puts)).toBe(0);
  await testInfo.attach('ux-fix-029-camera-evidence', { body: JSON.stringify({ canonical: saved.document.camera, before, interrupted, interruptedBytes, recovered }), contentType: 'application/json' });
  await page.screenshot({ path: testInfo.outputPath('ux-fix-029-recovery-canonical.png'), animations: 'disabled' });
});

test('completed-only area Finish and POI native previews reject at the byte cap while retaining or restoring unfinished work', async ({ page }, testInfo) => {
  await openInstrumentedMap(page);
  const full = await portableFixture(page);
  await openPortable(page, full);
  await expect(page.getByTestId('map-canvas')).toHaveAttribute('data-map-ready', 'true', { timeout: 30_000 });
  const saved = await savedAdmissionRecord(page);
  await page.evaluate(() => window.recoveryAudit.map!.jumpTo({ zoom: 11.123456 }));
  await page.getByRole('button', { name: 'Select Marker 5', exact: true }).click();
  const marker = page.getByRole('button', { name: 'Move Marker 5', exact: true });
  const before = await marker.boundingBox();
  expect(before).not.toBeNull();
  await marker.focus(); await marker.press('ArrowRight');
  await expect(page.locator('.map-route-editor-error')).toContainText('portable limit');
  const restored = await marker.boundingBox();
  expect(Math.hypot(restored!.x - before!.x, restored!.y - before!.y)).toBeLessThan(1);
  await page.getByRole('button', { name: 'Area (S)' }).click();
  await page.getByRole('tab', { name: 'Draw custom area' }).click();
  for (const [longitude, latitude] of [['16.35', '48.2'], ['16.38', '48.2'], ['16.38', '48.22']]) await addCoordinate(page, 'area', longitude, latitude);
  await page.getByRole('button', { name: 'Finish area', exact: true }).click();
  await expect(page.getByRole('status', { name: 'Area drawing status' })).toHaveText('3 vertices');
  await expect(page.getByRole('status', { name: 'Autosave status' })).toHaveText('Completed layers saved locally · Unfinished work not saved');
  const prompting = page.waitForEvent('dialog');
  const reloading = page.evaluate(() => location.reload());
  const prompt = await prompting;
  expect(prompt.type()).toBe('beforeunload');
  await prompt.dismiss(); await reloading;
  await expect(page.getByRole('status', { name: 'Area drawing status' })).toHaveText('3 vertices');
  expect(await savedAdmissionRecord(page)).toEqual(saved);
  await page.screenshot({ path: testInfo.outputPath('ux-fix-029-area-retained.png'), animations: 'disabled' });
});

test('compact backups in replacement and real cross-tab conflict dialogs do not automatically replace either document', async ({ page }, testInfo) => {
  await page.goto('./');
  await openPortable(page, await portableFixture(page, 'boundary'));
  const dialog = await stagePortable(page, await admissionFixture(page));
  const replacing = page.waitForEvent('download');
  await dialog.getByRole('button', { name: 'Download current project' }).click();
  const replacementBackup = await portableDownload(await replacing, testInfo, 'replacement-backup');
  expect(replacementBackup.document.layers).toHaveLength(201);
  expect(replacementBackup.bytes).toBeLessThan(MAX_PROJECT_FILE_BYTES);
  expect(Buffer.byteLength(JSON.stringify(replacementBackup.document, null, 2))).toBeGreaterThan(MAX_PROJECT_FILE_BYTES);
  await expect(dialog).toBeVisible();
  await dialog.getByRole('button', { name: 'Keep editing' }).click();
  const winner = await page.context().newPage();
  await winner.goto('./');
  await winner.getByRole('combobox', { name: 'Page preset' }).selectOption('A3');
  await expect(winner.getByRole('status', { name: 'Autosave status' })).toHaveText('All changes saved locally', { timeout: 30_000 });
  const saved = await storedDraft(winner);
  await page.getByRole('combobox', { name: 'Page preset' }).selectOption('A5');
  await expect(page.getByRole('status', { name: 'Autosave conflict notice' })).toBeVisible();
  const conflict = await reviewConflict(page);
  const backingUp = page.waitForEvent('download');
  await conflict.getByRole('button', { name: 'Download this tab’s version' }).click();
  const backup = await portableDownload(await backingUp, testInfo, 'conflict-backup');
  expect(backup.document.page.preset).toBe('A5');
  expect(backup.document.layers).toHaveLength(201);
  expect(backup.bytes).toBeLessThan(MAX_PROJECT_FILE_BYTES);
  await expect(conflict).toBeVisible();
  await expect(page.getByRole('status', { name: 'Conflict download status' })).toContainText('Download started');
  expect(await storedDraft(winner)).toEqual(saved);
  await page.screenshot({ path: testInfo.outputPath('ux-fix-029-compact-conflict.png'), animations: 'disabled' });
});

test('mobile rejected rename stays correctable inside a keyboard-scoped dialog without horizontal overflow', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('./');
  const full = await portableFixture(page);
  await openPortable(page, full);
  await page.getByRole('button', { name: 'Project', exact: true }).click();
  await page.getByRole('menuitem', { name: 'Rename project' }).click();
  const dialog = page.getByRole('dialog', { name: 'Rename project' });
  const title = dialog.getByRole('textbox', { name: 'Project name' });
  await title.fill(full.title + ' larger');
  await dialog.getByRole('button', { name: 'Rename', exact: true }).click();
  await expect(title).toHaveAttribute('aria-invalid', 'true');
  await expect(dialog.getByRole('alert')).toContainText('portable limit');
  await expect(title).toHaveValue(full.title + ' larger');
  await page.screenshot({ path: testInfo.outputPath('ux-fix-029-mobile-rename.png'), animations: 'disabled' });
  await dialog.getByRole('button', { name: 'Cancel' }).focus();
  await expect(dialog.getByRole('button', { name: 'Cancel' })).toBeFocused();
  await page.keyboard.press('p');
  await page.keyboard.press('ControlOrMeta+z');
  await expect(dialog).toBeVisible();
  expect(await dialog.evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true);
  await page.keyboard.press('Escape');
  await expect(page.getByRole('button', { name: 'Project', exact: true })).toBeFocused();
  await expect(page.getByRole('button', { name: 'Select (V)' })).toHaveAttribute('aria-pressed', 'true');
});
