import type { ProjectActions } from '../app/projectStoreContext';

export const PROJECT_ACTIONS = [
  'applyMapMatching',
  'createAdministrativeArea',
  'createIsochroneArea',
  'createDirectionsRoute',
  'replaceDirectionsRoute',
  'replaceRouteDraft',
  'transformRoute',
  'createPoi',
  'createPoiBatch',
  'createSearchPoi',
  'createRoute',
  'replaceAuthoredRoute',
  'createShape',
  'deleteLayer',
  'duplicateLayer',
  'importLayers',
  'insertRouteVertex',
  'moveLayer',
  'setProjectTitle',
  'renameLayer',
  'replaceLayerFromImport',
  'selectLayer',
  'setCameraBearing',
  'setCameraViewport',
  'setMapAreaLocked',
  'setCameraPitch',
  'setPageDimension',
  'setPageBoundaryVisible',
  'setPageOrientation',
  'setPagePreset',
  'setLayerAppearance',
  'setRouteMarker',
  'setRouteSegmentStyle',
  'setPoiCoordinates',
  'setPoiCustomMarker',
  'setRouteVertex',
  'setArcSegmentCurvature',
  'setShapeGeometry',
  'setShapeVertex',
  'setLayerOpacity',
  'setMapStyle',
  'setMapStyleAdjustment',
  'setMapStyleColor',
  'setMapStyleTone',
  'resetMapStyle',
  'resetMapStyleCustomization',
  'setMapLanguage',
  'setMapTextScale',
  'setMapFeatureVisibility',
  'toggleLayerVisibility',
  'toggleLayerLock',
  'undo',
  'redo',
  'removeRouteVertex',
  'replaceRouteGeometry',
] as const satisfies readonly (keyof ProjectActions)[];

export type ProjectAnalyticsAction = typeof PROJECT_ACTIONS[number];
